config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
]

pages/urls.py
from django.urls import path

from .views import HomeView


app_name = 'pages'


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('home/', HomeView.as_view(), name='home'),
]

accounts/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from authtools.models import AbstractEmailUser


class User(AbstractEmailUser):
    full_name = models.CharField('full name', max_length=255)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

pages/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render

# Create your views here.

pages/views.py
from django.views.generic import TemplateView

from .mixins import HomePage


class HomeView(HomePage, TemplateView):
    template_name = 'pages/home.html'

pages/templates/pages/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<!--[if IE 9]>
<html class="ie9" lang="en">    <![endif]-->
<!--[if IE 8]>
<html class="ie8" lang="en">    <![endif]-->
<head>
   <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name=viewport content="width=device-width, initial-scale=1">

   <title>Eyob Tariku {% if page_title %} | {{ page_title }} {% endif %}</title>

   <meta name="description" content="{{ page_description }}">
   <meta name="keywords" content="">
   <meta name="author" content="Eyob Tariku <eyobtariku@gmail.com>">

   <!-- Preloader -->
   <link href="{% static 'assets/custom/2.2.0/css/preloader.css' %}" property='stylesheet' rel="stylesheet" type="text/css" media="screen"/>

   <!-- CSS -->
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous" media="screen">
   <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" property='stylesheet' rel="stylesheet" type="text/css" media="screen"/>
   <link href="{% static 'assets/vendor/flaticons/flaticon.min.css' %}" property='stylesheet' rel="stylesheet" type="text/css" media="screen"/>
   <link href="{% static 'assets/vendor/hover/css/hover-min.css' %}" property='stylesheet' rel="stylesheet" type="text/css" media="screen"/>
   <link href="{% static 'assets/vendor/mfp/css/magnific-popup.min.css' %}" property='stylesheet' rel="stylesheet" type="text/css" media="screen"/>
   <link href="{% static 'assets/vendor/owl-carousel/assets/owl.carousel.min.css' %}" property='stylesheet' rel="stylesheet" type="text/css" media="screen"/>

   <!-- More CSS vendor libraries -->
   {% block more-css-vendors %} {% endblock %}

   <!-- Base styles -->
   <link href="{% static 'assets/custom/2.2.0/css/style.css' %}" property='stylesheet' rel="stylesheet" type="text/css" media="screen"/>
   <link href="{% static 'assets/custom/2.2.0/css/layouts/samuel.css' %}" property='stylesheet' rel="stylesheet" type="text/css" media="screen"/>
   <link href="{% static 'assets/custom/2.2.0/css/colors/default.css' %}" id="color-styles" property='stylesheet' rel="stylesheet" type="text/css" media="screen"/>

   <!-- Additional Styles & Head tags -->
   {% block custom-head %}{% endblock %}
</head>

<body id="samuel" class="boxed">

<!--Pre-Loader-->
<div id="preloader"></div>

{% block page-header %}
<header>
 <section id="top-navigation" class="container-fluid nopadding">
  <div class="row nopadding ident ui-bg-color01">
     <!-- Photo -->
     <a href="index.html">
        <div class="col-md-4 vc-photox photo-01">&nbsp;</div>
     </a>
     <!-- /Photo -->
     <div class="col-md-8 vc-name nopadding">
        <!-- Name-Position -->
        <div class="row nopadding name">
           <div class="col-md-10 name-title"><h1 class="font-accident-two-extralight">Eyob Tariku</h1></div>
           <div class="col-md-2 nopadding name-pdf">
              <a href="#" class="hvr-sweep-to-right"><i class="flaticon-download149" title="Download CV.pdf"></i></a>
           </div>
        </div>
        <div class="row nopadding position">
           <div class="col-md-10 position-title">

              <section class="cd-intro">

                <!-- Slide Banner Section -->
                {% block slide-banner %}
                 <h2 class="cd-headline clip is-full-width font-accident-two-light">
                    <span>The Experienced </span>
                    <span class="cd-words-wrapper">
                       <b class="is-visible">Software Developer</b>
                       <b>Back-End Engineer</b>
                       <b>Database Designer</b>
                    </span>
                 </h2>
                {% endblock slide-banner %}
              </section>

           </div>
           <div class="col-md-2 nopadding pdf">
              <a href="#" class="hvr-sweep-to-right"><i class="flaticon-linkedin22" title="My Linkedin Profile"></i></a>
           </div>
        </div>
        <!-- /Name-Position -->

        <!-- Main Navigation -->
        {% block main-navigation %}
        <ul id="nav" class="row nopadding cd-side-navigation">
           <li class="col-xs-4 col-sm-2 nopadding menuitem ui-menu-color01" data-animation-duration="1000" data-animation-delay="100">
              <a href="{% url 'pages:home' %}" class="hvr-sweep-to-bottom"><i class="flaticon-insignia"></i><span>home</span></a>
           </li>
           <li class="col-xs-4 col-sm-2 nopadding menuitem ui-menu-color02" data-animation-duration="1000" data-animation-delay="300">
              <a href="#" class="hvr-sweep-to-bottom"><i class="flaticon-graduation61"></i><span>resume</span></a>
           </li>
           <li class="col-xs-4 col-sm-2 nopadding menuitem ui-menu-color03" data-animation-duration="1000" data-animation-delay="500">
              <a href="#" class="hvr-sweep-to-bottom"><i class="flaticon-book-bag2"></i><span>portfolio</span></a>
           </li>
           <li class="col-xs-4 col-sm-2 nopadding menuitem ui-menu-color04" data-animation-duration="1000" data-animation-delay="700">
              <a href="#" class="hvr-sweep-to-bottom"><i class="flaticon-placeholders4"></i><span>contacts</span></a>
           </li>
           <li class="col-xs-4 col-sm-2 nopadding menuitem ui-menu-color05" data-animation-duration="1000" data-animation-delay="900">
              <a href="#" class="hvr-sweep-to-bottom"><i class="flaticon-earphones18"></i><span>feedback</span></a>
           </li>
           <li class="col-xs-4 col-sm-2 nopadding menuitem ui-menu-color06" data-animation-duration="1000" data-animation-delay="1100">
              <a href="#" class="hvr-sweep-to-bottom"><i class="flaticon-pens15"></i><span>blog</span></a>
           </li>
        </ul>
        {% endblock main-navigation %}
        <!-- /Main Navigation -->

     </div>
  </div>
 </section>
</header>
{% endblock page-header %}

<!-- Container -->
<div class="content-wrap">
 {% block content %}
 {% endblock content %}
</div>


<!-- Footer Section -->
{% block page-footer %}
<footer class="padding-50 dark ui-bg-color01"
        data-animation-origin="top"
        data-animation-duration="500"
        data-animation-delay="800"
        data-animation-distance="50px">
   <div class="container-fluid nopadding">
      <div class="row">
         <div class="col-sm-3">
            <h5 class="font-accident-two-bold uppercase">About ME</h5>
            <p class="inline-block">
               Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt optio et quas, vero quod.
            </p>
            <div class="divider-dynamic"></div>
         </div>
         <div class="col-sm-3 cv-link">
            <h5 class="font-accident-two-bold uppercase">Download cv</h5>
            <div class="dividewhite1"></div>
            <a href="#!"><i class="fa fa-long-arrow-down" aria-hidden="true"></i>English</a>
            <a href="#!"><i class="fa fa-long-arrow-down" aria-hidden="true"></i>Amharic</a>
            <p class="inline-block">
               The CV is in .pdf format. Use the Adobe Reader to open it.
            </p>
            <div class="divider-dynamic"></div>
         </div>
         <div class="col-sm-3">
            <h5 class="font-accident-two-bold uppercase">Subscribe Now</h5>
            <div class="dividewhite1"></div>
            <input class="newsletter-email" type="email" required="" name="ne" placeholder="Your Email">
            <a href="#!" class="btn btn-wh-trans btn-xs">OK</a>
            <div class="divider-dynamic"></div>
         </div>
         <div class="col-sm-3">
            <h5 class="font-accident-two-bold uppercase">Follow me</h5>
            <div class="follow">
               <ul class="list-inline social">
                  <li><a target="_blank" href="#" class="rst-icon-facebook"><i class="fa fa-facebook"></i></a></li>
                  <li><a target="_blank" href="#" class="rst-icon-twitter"><i class="fa fa-twitter"></i></a></li>
                  <li><a target="_blank" href="#" class="rst-icon-linkedin"><i class="fa fa-linkedin"></i></a></li>
                  <li><a target="_blank" href="#" class="rst-icon-instagram"><i class="fa fa-instagram"></i></a></li>
                  <li><a target="_blank" href="#" class="rst-icon-youtube"><i class="fa fa-youtube"></i></a></li>
               </ul>
            </div>
            <div class="divider-dynamic"></div>
         </div>
      </div>
      <div class="dividewhite1"></div>
      <div class="row">
         <div class="col-md-12 copyrights">
            <p>&copy; {% now 'Y' %} Eyob Tariku.</p>
         </div>
      </div>
   </div>
</footer>
{% endblock page-footer %}

<!-- Back to Top -->
<div id="back-top"></div>
<!-- /Back to Top -->

<!-- JS -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="https://npmcdn.com/imagesloaded@4.1/imagesloaded.pkgd.min.js"></script>
<script src="https://unpkg.com/isotope-layout@3.0/dist/isotope.pkgd.min.js"></script>
<script src="https://unpkg.com/scrollreveal@3.3.2/dist/scrollreveal.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/velocity/1.2.3/velocity.min.js"></script>

<script src="{% static 'assets/vendor/mfp/js/jquery.magnific-popup.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/vendor/progressbar/progressbar.min.js' %}" type="text/javascript"></script>

<script src="{% static 'assets/vendor/anicounter/jquery.counterup.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/vendor/pjax/jquery.pjax.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/vendor/owl-carousel/owl.carousel.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/vendor/headlines/headlines.min.js' %}" type="text/javascript"></script>

<!-- More JavaScript Vendors -->
{% block more-js-vendors %} {% endblock %}

<!-- Custom scripts -->
<script src="{% static 'assets/custom/2.2.0/js/animation.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/custom/2.2.0/js/custom.js' %}" type="text/javascript"></script>

<!-- Custom JS Scripts -->
{% block custom-js %} {% endblock %}

</body>

</html>

pages/templates/pages/home.html
{% extends 'pages/base.html' %}

{% block content %}
<section class="container-fluid" data-section="home">

   <!-- Personal Flexy Section -->
   <div class="row flex-row">
      <!-- Personal Details 01 -->
      <div id="details" class="col-md-8 flex-column bg-color01 light nopadding"
           data-animation-origin="left"
           data-animation-duration="300"
           data-animation-delay="400"
           data-animation-distance="200px">
         <div class="padding-50 flex-panel">
            <div class="row row-no-padding">
               <div class="col-md-12 nopadding">
                  <h3 class="font-accident-two-normal uppercase title">Gridus Resume HTML Template</h3>
                  <div class="quote">
                     <h4 class="font-accident-two-normal uppercase subtitle">Perfect for CV / Resume or Portfolio Website</h4>
                     <div class="dividewhite3"></div>
                  </div>
               </div>
            </div>
            <div class="divider-dynamic"></div>
            <div class="row nopadding">
               <div class="col-md-4 infoblock nopadding">
                  <div class="row">
                     <div class="col-xs-12 col-sm-1 col-md-3"><i class="flaticon-clocks18 color-blue"></i><div class="dividewhite1"></div></div>
                     <div class="col-xs-12 col-sm-11 col-md-9">
                        <h4 class="font-accident-two-medium uppercase">Modern</h4>
                        <p class="">
                           The Gridus Resume Template has an unique modern flat intuitive design. You can choose one of 8 Color schemes.
                        </p>
                     </div>
                  </div>
                  <div class="divider-dynamic"></div>
               </div>
               <div class="col-md-4 infoblock nopadding">
                  <div class="row">
                     <div class="col-xs-12 col-sm-1 col-md-3"><i class="flaticon-pie-graph color-blue"></i><div class="dividewhite1"></div></div>
                     <div class="col-xs-12 col-sm-11 col-md-9">
                        <h4 class="font-accident-two-medium uppercase">Simple CV</h4>
                        <p class="">
                           Gridus Personal Template is the simple, clean and stylish fully-responsive resume theme with modern creative design.
                        </p>
                     </div>
                  </div>
                  <div class="divider-dynamic"></div>
               </div>
               <div class="col-md-4 infoblock nopadding">
                  <div class="row">
                     <div class="col-xs-12 col-sm-1 col-md-3"><i class="flaticon-tool-1 color-blue"></i><div class="dividewhite1"></div></div>
                     <div class="col-xs-12 col-sm-11 col-md-9">
                        <h4 class="font-accident-two-medium uppercase">Responsive</h4>
                        <p class="">
                           Works fast and looks fine on any device with the wide range of the screen resolution. Supports all the Google SEO rules.
                        </p>
                     </div>
                  </div>
                  <div class="divider-dynamic"></div>
               </div>

            </div>
         </div>
      </div>
      <!-- /Personal Details 01 -->

      <!-- Personal Details 02 -->
      <div id="personal" class="col-md-4 flex-column light ui-block-color01 personal"
           data-animation-origin="right"
           data-animation-duration="500"
           data-animation-delay="600"
           data-animation-distance="100px">
         <div class="padding-50 flex-panel">
            <h3 class="font-accident-two-normal uppercase title">Personal Info</h3>
            <div class="dividewhite4"></div>
            <div>
               <div class="fullwidth box">
                  <div class="one"><p class="uppercase">Name:</p></div>
                  <div class="two"><p class="">Eyob Tariku</p></div>
               </div>
               <div class="fullwidth box">
                  <div class="one"><p class="uppercase">Address:</p></div>
                  <div class="two"><p class="">Anat Building 2nd Floor, Bole Sub-city, Addis Ababa</p></div>
               </div>
               <div class="fullwidth box">
                  <div class="one"><p class="uppercase">Phone:</p></div>
                  <div class="two"><p class="">+251 911 42 78 05</p></div>
               </div>
               <div class="fullwidth box">
                  <div class="one"><p class="uppercase">Email:</p></div>
                  <div class="two"><p class="">eyobtariku@gmail.com</p></div>
               </div>
            </div>
            <div class="dividewhite1"></div>
         </div>
      </div>
      <!-- /Personal Details 02 -->
   </div>
   <!-- /Personal Flexy Section -->

</section>

<section id="professional" class="container-fluid" data-section="home">

   <div class="row flex-row">

      <div id="pro-experience" class="col-md-4 flex-column dark nopadding ui-block-color02 flex-col"
           data-animation-origin="bottom"
           data-animation-duration="300"
           data-animation-delay="800"
           data-animation-distance="200px">
         <div class="padding-50 flex-panel">
            <h3 class="font-accident-two-normal uppercase title">Employment</h3>
            <div class="dividewhite4"></div>
            <div class="experience">
               <ul class="">
                  <li class="date">02/2008 - 04/2010</li>
                  <li class="company uppercase">
                     <a>
                        ABC Brodcast Inc. New York.
                     </a>
                  </li>
                  <li class="position">Junior Designer</li>
               </ul>
               <ul class="">
                  <li class="date">04/2010 - 06/2012</li>
                  <li class="company uppercase">
                     <a>
                        Leo Burnett London Office
                     </a>
                  </li>
                  <li class="position">Senior Designer</li>
               </ul>
               <ul class="">
                  <li class="date">06/2012 - present</li>
                  <li class="company uppercase">
                     <a>
                        Google Inc. Dublin.
                     </a>
                  </li>
                  <li class="position">UI/UX Designer</li>
               </ul>
            </div>
            <a href="resume.html" class="btn btn-wh-trans btn-xs">Learn More</a>
            <div class="dividewhite1"></div>
         </div>
      </div>
      <div id="circle-skills" class="col-md-8 flex-column dark nopadding ui-block-color03 flex-col" data-section="progress"
           data-animation-origin="right"
           data-animation-duration="400"
           data-animation-delay="1100"
           data-animation-distance="200px">
         <div class="padding-50 flex-panel">
            <h3 class="font-accident-two-normal uppercase title">Professional skills</h3>
            <div class="dividewhite1"></div>
            <div class="row">

               <div class="col-md-4 col-sm-4 col-xs-12 nopadding">
                  <div class="progressbar text-center">
                     <div id="circle1"
                          data-progressbar="circle"
                          data-progressbar-color="#fff"
                          data-progressbar-trailcolor="#fff"
                          data-progressbar-to='{"color": "#51f2ec", "width": 4}'
                          data-progressbar-from='{"color": "#3498db", "width": 4}'
                          data-progressbar-value="0.6">
                     </div>
                     <h4 class="font-accident-two-bold uppercase">Install</h4>
                     <p class="font-regular-normal">
                        A prototype is an early sample, model, or release of a product built to test ...
                     </p>
                     <a href="resume.html" class="btn btn-wh-trans btn-xs">Learn More</a>
                  </div>
                  <div class="dividewhite1"></div>
               </div>

               <div class="col-md-4 col-sm-4 col-xs-12 nopadding">
                  <div class="progressbar text-center">
                     <div id="circle2"
                          data-progressbar="circle"
                          data-progressbar-color="#fff"
                          data-progressbar-trailcolor="#fff"
                          data-progressbar-to='{"color": "#ffd200", "width": 4}'
                          data-progressbar-from='{"color": "#3498db", "width": 4}'
                          data-progressbar-value="0.85">
                     </div>
                     <h4 class="font-accident-two-bold uppercase">Customize</h4>
                     <p class="font-regular-normal">
                         Design is the creation of a plan or convention for the construction of an object ...
                     </p>
                     <a href="resume.html" class="btn btn-wh-trans btn-xs">Learn More</a>
                  </div>
                  <div class="dividewhite1"></div>
               </div>

               <div class="col-md-4 col-sm-4 col-xs-12 nopadding">
                  <div class="progressbar text-center">
                     <div id="circle3"
                          data-progressbar="circle"
                          data-progressbar-color="#fff"
                          data-progressbar-trailcolor="#fff"
                          data-progressbar-to='{"color": "#F09C88", "width": 4}'
                          data-progressbar-from='{"color": "#3498db", "width": 4}'
                          data-progressbar-value="0.93">
                     </div>
                     <h4 class="font-accident-two-bold uppercase">Support</h4>
                     <p class="font-regular-normal">
                         Software development is the process of computer programming ...
                     </p>
                     <a href="resume.html" class="btn btn-wh-trans btn-xs">Learn More</a>
                  </div>
                  <div class="dividewhite1"></div>
               </div>

            </div>
         </div>
      </div>

   </div>

</section>
{% endblock content %}